meta:
  version: 3
  flow: Chip
  substituting_steps:

    # Magic reports some overlaps which can be ignored
    Checker.IllegalOverlap: null

    # Disable KLayout DRC
#    #KLayout.DRC: null
#    #Checker.KLayoutDRC: null

    # Disable magic DRC
#    #Magic.DRC: null
#    #Checker.MagicDRC: null
#    #Magic.StreamOut: null
#    #Magic.GDSIIStreamOut: null
    # Disable KLayout antenna check
#    #KLayout.Antenna: null
#    #Checker.KLayoutAntenna: null

    # Disable KLayout density check
#    #KLayout.Density: null
#    #Checker.KLayoutDensity: null
    
    # Save time
#    #OpenROAD.IRDropReport: null
#    #KLayout.XOR: null
#    #Netgen.LVS: null
#    #Checker.LVS: null

MAGIC_CAPTURE_ERRORS: False

DESIGN_NAME: RFID4410
VERILOG_FILES:
- dir::../src/anti_collision.v
- dir::../src/crc.v
- dir::../src/decoder.v
- dir::../src/digital_block_02.v
- dir::../src/digital_block_05.v
- dir::../src/digital_block_06.v
- dir::../src/digital_block_07.v
- dir::../src/digital_block_09.v
- dir::../src/digital_block_12.v
- dir::../src/encoder.v
- dir::../src/freq_div.v
- dir::../src/fsm.v
- dir::../src/rom.v
- dir::../src/sram_256x32_rw.v
- dir::../src/test_block.v
- dir::../src/timer.v
- dir::../src/top_module.v
- dir::../src/RFID4410.v


VERILOG_DEFINES: [FUNCTIONAL]


# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# Specify the pad instances for the padring
PAD_SOUTH: [
    iovdd_pad_s,
    iovss_pad_s,
    vdd_pad_s,
    vss_pad_s,      
    vdd_pad_n,
    vss_pad_n,
    clk_pad,
    tx_out_pad
]

PAD_EAST: [              
    DFT_S0_pad,
    DFT_S1_pad,
    DFT_S2_pad,
    DFT_EN_pad,
    analog_CLK_pad, 
    analog_RESET_pad,   
    analog_VDD_pad,
    analog_V_BGR_pad
]

PAD_NORTH: [
    clk_out_pad,
    rx_in_pad,
    rst_n_pad,
    test_mode_pad, 
    analog_ANTENNA1_pad,
    analog_ANTENNA2_pad,  
    analog_VBIASP_pad,       
    analog_DFT_pad
]

PAD_WEST: [
     
    "force_state_pads\\[0\\].force_state_pad",
    "force_state_pads\\[1\\].force_state_pad",
    "force_state_pads\\[2\\].force_state_pad",
    "force_state_pads\\[3\\].force_state_pad",
    "state_dbg_pads\\[0\\].state_dbg_pad",
    "state_dbg_pads\\[1\\].state_dbg_pad",
    "state_dbg_pads\\[2\\].state_dbg_pad",
    "state_dbg_pads\\[3\\].state_dbg_pad"
    

]

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# Clock
CLOCK_PORT: clk_PAD
CLOCK_NET: clk_pad/p2c

CLOCK_PERIOD: 73.7

# Floorplanning
FP_SIZING: absolute


DIE_AREA: [0, 0, 1414, 1414]
CORE_AREA: [365, 365, 1049, 1049]

# Increase for more logic
# on your die
PL_TARGET_DENSITY_PCT: 18
GRT_ALLOW_CONGESTION: true

# PDN
PDN_CORE_RING: True

# Override bondpad name
PAD_BONDPAD_NAME: bondpad_70x70_novias

# Bondpad is not yet included in the PDK
EXTRA_GDS:
- dir::../ip/bondpad_70x70/gds/bondpad_70x70.gds
- dir::../ip/bondpad_70x70_novias/gds/bondpad_70x70_novias.gds

EXTRA_LEFS:
- dir::../ip/bondpad_70x70/lef/bondpad_70x70.lef
- dir::../ip/bondpad_70x70_novias/lef/bondpad_70x70_novias.lef

IGNORE_DISCONNECTED_MODULES:
- bondpad_70x70
- bondpad_70x70_novias

# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 15
PDN_CORE_RING_HWIDTH: 15
# Ensure minimum spacing for long metals
PDN_CORE_RING_VSPACING: 5
PDN_CORE_RING_HSPACING: 5

PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False	


MAGIC_EXT_UNIQUE: notopports

MACROS:
  RM_IHPSG13_1P_256x32_c2_bm_bist:
    gds:
      - pdk_dir::libs.ref/sg13g2_sram/gds/RM_IHPSG13_1P_256x32_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13g2_sram/lef/RM_IHPSG13_1P_256x32_c2_bm_bist.lef
    vh:
      - pdk_dir::libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_256x32_c2_bm_bist.v
      - pdk_dir::libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_core_behavioral_bm_bist.v
    lib:
      "*_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_256x32_c2_bm_bist_typ_1p20V_25C.lib
      "*_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_256x32_c2_bm_bist_fast_1p32V_m55C.lib
      "*_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_256x32_c2_bm_bist_slow_1p08V_125C.lib
    instances:
      u_top_module.u_digital_block_14.u_sram:
        location: [390, 390]
        orientation: S
        
  TOP_ANALOG:
    gds:
      - dir::../ip/TOP_ANALOG/gds/TOP_ANALOG.gds
    lef:
      - dir::../ip/TOP_ANALOG/lef/TOP_ANALOG.lef
    vh:
      - dir::../ip/TOP_ANALOG/vh/TOP_ANALOG.v
    
    instances:
      u_TOP_ANALOG:
        location: [749, 928]
        orientation: N
      
        
PDN_OBSTRUCTIONS:
  - [TopMetal1, 749, 928, 1019, 1025]
  - [TopMetal2, 749, 928, 1019, 1025]

 
# This is an alternative method compared to
# specifying the power connections in the RTL
PDN_MACRO_CONNECTIONS:
- "u_top_module.u_digital_block_14.u_sram VDD VSS VDDARRAY! VSS!"
- "u_top_module.u_digital_block_14.u_sram VDD VSS VDD! VSS!"
- "u_TOP_ANALOG IOVDD IOVSS IOVDD VSS"

SYNTH_POWER_DEFINE: "USE_POWER_PINS"

FP_MACRO_HORIZONTAL_HALO: 25
FP_MACRO_VERTICAL_HALO: 25

PDN_CFG: dir::pdn_cfg.tcl

