# Generated by kpex 0.3.8
crashbackups stop
drc off
gds read /foss/designs/simulations/Post_layout/layout_POR.gds
load layout_POR
select top cell
flatten layout_POR_flat
load layout_POR_flat
cellname delete layout_POR -noprompt
cellname rename layout_POR_flat layout_POR
select top cell
extract path /foss/designs/simulations/Post_layout/output/layout_POR__layout_POR/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/simulations/Post_layout/output/layout_POR__layout_POR/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/simulations/Post_layout/output/layout_POR__layout_POR/magic_RC -o /foss/designs/simulations/Post_layout/output/layout_POR__layout_POR/magic_RC/layout_POR.pex.spice
quit -noprompt
