# Generated by kpex 0.3.8
crashbackups stop
drc off
gds read /foss/designs/Layout2026/Clock_Extractor_2026.gds
load Clock_Extractor_2026
select top cell
flatten Clock_Extractor_2026_flat
load Clock_Extractor_2026_flat
cellname delete Clock_Extractor_2026 -noprompt
cellname rename Clock_Extractor_2026_flat Clock_Extractor_2026
select top cell
extract path /foss/designs/Layout2026/output/Clock_Extractor_2026__Clock_Extractor_2026/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/Layout2026/output/Clock_Extractor_2026__Clock_Extractor_2026/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/Layout2026/output/Clock_Extractor_2026__Clock_Extractor_2026/magic_RC -o /foss/designs/Layout2026/output/Clock_Extractor_2026__Clock_Extractor_2026/magic_RC/Clock_Extractor_2026.pex.spice
quit -noprompt
